services:
  remotettys:
    image: ghcr.io/finch-xu/remotettys:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
